# Generated by Django 3.2.7 on 2021-10-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.CharField(max_length=50)),
                ('temp', models.IntegerField(default=0)),
                ('light', models.IntegerField(default=0)),
                ('other', models.CharField(max_length=60)),
                ('time_occured', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
