# Generated by Django 3.2.8 on 2021-10-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_weather'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='temp',
            new_name='water',
        ),
    ]
