# Generated by Django 3.2.8 on 2021-10-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_rename_temp_weather_water'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='api',
            field=models.CharField(default=23456, max_length=50),
            preserve_default=False,
        ),
    ]
