# Generated by Django 3.2.8 on 2021-10-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_weather_api'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='api',
            new_name='ip',
        ),
    ]
