# Generated by Django 3.2.8 on 2021-10-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_rename_api_weather_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='weather',
            name='ip',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='weather',
            name='light',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='weather',
            name='other',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='weather',
            name='water',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
