# Generated by Django 3.2.8 on 2021-10-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_auto_20211026_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.IntegerField(blank=True, max_length=50),
        ),
    ]
